### ISSUE TITLE
Cannot access container on port 443, can't login on community forum either

### ISSUE THREAD

**Issue by Extarys** [serversideup/financial-freedom#52]
[[I tried signing with GH on https://id.serversideup.net/ but it won't work. I tried making a new account but it said the email is in use by GH. I tried resetting the password but it said the same thing. I have no access to create a post on the community forum. Sorry to bother you here]]

Following https://community.serversideup.net/t/how-do-i-setup-financial-freedom-in-a-docker-container/568

- When I clone the repo and create the container, port 80 and 443 are available (`docker ps -a`), but 443 return "Unable to connect". I have no idea how to test FF and ditch firefly-iii. Is there new development on how to run and test financial-freedom? I'm very excited! 

- Is there also a way to remove my account on the community forum so I can create an ordinary one?

**Comment by danpastori** [comment]
@Extarys Sorry for the inconvenience on signing in. We had an issue after we updated our platform and it should be fixed. Shoot us an email with the email you used on our platform:
```
support at serversideup dot net
```
We will then get everything fixed up and you can make an account. Thanks for reaching out though, we want to make sure it's as seamless as possible!
