### ISSUE TITLE
Unable to register

### ISSUE THREAD

**Issue by connor11528** [serversideup/financial-freedom#53]
## Issue description
Unable to register. Input does not submit to server. Maybe this is due to an environment issue. The register.blade.php file looks like pretty boilerplate Jetstream. Wanted to log it in case other people experienced this issue too..

## Environment

- Local on mac, latest Chrome.

## Steps to reproduce the issue

1.  Head to https://financial-freedom.dev.test/register
2.  Submit information
3.  See error

## What is expected?
Information should submit

## Additional details / screenshots
<img width="1460" alt="Screen Shot 2022-04-08 at 5 14 41 PM" src="https://user-images.githubusercontent.com/3578908/162549575-84f32600-852e-4bbe-b407-183adb03af9d.png">

**Comment by claybitner** [comment]
This is happening for me too.

**Comment by danpastori** [comment]
Ah I think this has something to do with the upgrade to the Vue 3 version of Inertia. Something was wrong with `v-model`. Let me take a look and see what I can come up with.

**Comment by danpastori** [comment]
@claybitner & @connor11528 ,

The registration issue is fixed. It was something to do with the JetStream inputs not handling the upgrade to Vue 3 correctly. If you pull the new version, you should be able to register. There's still a lot of WIP, but would love to hear feedback.

**Comment by connor11528** [comment]
Okay awesome thanks @danpastori! I'll give it another go 📈
