### ISSUE TITLE
Create a docker hub image for easy deployments

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/financial-freedom#56]
# Problem
- There is no official image for Financial Freedom

# Proposed solution
- Create a Docker Image that can be published

**Comment by Gitoffomalawn** [comment]
Is there any documentation on how to work with the image you made? I'd like to run some tests with it.

**Comment by jaydrogers** [comment]
Still working on that. Track my progress here: https://github.com/serversideup/financial-freedom/pull/57

I am looking to have this ready in early 2023 👍

**Comment by Emuzex** [comment]
Hi :) Is this project still maintained?

**Comment by jaydrogers** [comment]
Check the pinned issue for more details: https://github.com/serversideup/financial-freedom/issues/58#issuecomment-1474130024
