### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by jeremykenedy** [serversideup/financial-freedom#58]
Is this project still alive??

**Comment by jaydrogers** [comment]
This was a side project that took off faster than we expected. It got over 600 stars and we never really talked about it 😅

### Where we're at
This project definite _is not dead_. We plan to revisit with a whole new perspective once we finish up our current commitments:

- **Our book** ([The Ultimate Guide to Building APIs & SPAs](https://serversideup.net/ultimate-guide-to-building-apis-and-spas-with-laravel-and-nuxt3/)) is on schedule to be complete in May 2023
- **Our SaaS** ([Bugflow](https://bugflow.io/)) is expected to have it's first customers by May or June

Once we get through those, expect A LOT of movement in this group. Although the GitHub may be quiet in the time being, we have pages and pages of notes to bring this project to the next level

### If people want this product faster
obviously that isn't possible with financial backing. Right now our income is supplemented by client work -- meaning we need to work on those projects to pay for our living expenses.

We're hoping the traction with our book and SaaS will help, but sponsorships do too: https://github.com/sponsors/serversideup

Thanks for your patience as we get through our backlog of work! 😅🏃‍♂️

**Comment by jeremykenedy** [comment]
Cool, I think about contributing but noticed PRs had no movement and there is a lot of placeholders in the drawer nav so that's where my question stemmed from. Thank!

**Comment by jeremykenedy** [comment]
I feel your pain, I'm one guy supporting a bunch packages while working a day job. It's fun, rewarding (not in a financial way), yet a ton of work and energy. 

Thanks for the reply and open source work!
