### ISSUE TITLE
Design Landing Page

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/financial-freedom#89]
![Image](https://github.com/serversideup/financial-freedom/assets/3174134/242eb7c2-d841-4ae3-b5a6-1ae920a77ec7)

# 🎨Design File
[Access Figma File →](https://www.figma.com/file/JIJGYut8HuSyYourCsgy1J/Financial-Freedom-Designs?type=design&node-id=8723-151413&mode=design&t=7Dsg16y2q7VuvdZw-11)

# ⚡️ Page Notes

### Navigation
![Image](https://github.com/serversideup/financial-freedom/assets/3174134/d8640c74-6b7a-4692-8bfa-168d41cc2939)

- [x] Link logo to financialfreedom.app
- [x] Link Docs page to Nuxt Content page
- [x] Discord should be linked to https://serversideup.net/discord
- [x] "Star on GitHub" should go to https://github.com/serversideup/financial-freedom
- [x] "Get Notified " should go to our email list sign up (maybe an external ConvertKit page? @danpastori: I can make a quick page where they can sign up if you want the branding to match better)
- [x] Make the header sticky and transparent on scroll (like we did for serversideup/php)
- [x] Favicon is [located here](https://www.figma.com/file/JIJGYut8HuSyYourCsgy1J/Financial-Freedom-Designs?type=design&node-id=8737-43115&mode=design&t=7Dsg16y2q7VuvdZw-11)

### Convert Kit & Sign Up
<img width="1145" alt="image" src="https://github.com/serversideup/financial-freedom/assets/3174134/f47cee93-3caa-4701-8234-43c0577d28cd">

- [x] Add the user to our main Server Side Up list
- [x] Tag them as "financial-freedom"
- [x] Feel free to whip together a welcome email (@danpastori: I can help write this if needed, just let me know)

### Social Image
- [ ] Ensure social image is designed and working with Twitter

### Footer
<img width="1459" alt="image" src="https://github.com/serversideup/financial-freedom/assets/3174134/da5422b3-b086-4a42-9da8-9c8c0107f2f8">

- [ ] Use a very similar footer as serversideup/php
- [ ] On hover, feel free to make that section look cool and pick any colors you think is best. We can always adjust if needed

# Mobile
[📲 Mobile specific designs →](https://www.figma.com/file/JIJGYut8HuSyYourCsgy1J/Financial-Freedom-Designs?type=design&node-id=8723-152402&mode=design&t=7Dsg16y2q7VuvdZw-11)

### Overall notes
- Mainly everything is the same, but some text may scale down

### Mobile navigation
<img width="834" alt="image" src="https://github.com/serversideup/financial-freedom/assets/3174134/f9a22868-f304-4c3e-9991-652808baaf4a">

- [ ] Show a hamburger menu

<img width="250" alt="image" src="https://github.com/serversideup/financial-freedom/assets/3174134/aca89117-1573-4540-980f-43de90fa48b0">

- [ ] On expand, have the menu behave similar to serversideup/php

**Comment by jaydrogers** [comment]
@danpastori: The above page is ready for development. Let me know if you have any questions 🎉

**Comment by danpastori** [comment]
@jaydrogers I link the "Get Notified" buttons to the form on the landing page for now. If you want to make a quick convert kit form landing page, I can do that. Just let me know.

**Comment by danpastori** [comment]
@jaydrogers for now, I just removed the search link. I'm going to get it working in https://github.com/serversideup/docker-php/issues/131 first. When we develop content we can submit to Algolia instant search, get our keys and have something to index.
