### ISSUE TITLE
Update designs for Docs page

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/financial-freedom#90]
### Problem
![Image](https://github.com/serversideup/financial-freedom/assets/3174134/b6a419a7-a54c-4411-bf1e-458786e45177)

- We need a docs page to work well 
- I started to change some colors, but then we switched to dark mode

### Proposed Solution
- Instead of me going through a whole Figma design, could we just adjust the colors on the fly and see how it turns out?

Adjusting on the fly might save a lot of tedious tasks. I am pretty sure the Tailwind Template came with a sweet dark mode too.

@danpastori: Hit me up if you have any questions on this or if you don't like this approach

**Comment by danpastori** [comment]
@jaydrogers I updated the colors to just match the home screen a little better. We can make any changes as we add more content.
