### ISSUE TITLE
Cannot find module './Auth/Login'

### ISSUE THREAD

**Issue by sidis405** [serversideup/financial-freedom#93]
## Issue description
Hi folks

the project looks great and promising so i wanted to take it for a spin.
After building and configuring the project, i can't seem to be able to access any routes.

Note: i can see the Pages/Pages-old folders so i assume there's a undergoing process.
:)

## Environment

Locally on Mac Sonoma, php8.1. 
Browser: Brave (but reproducible on Chrome, Safari and FIrefox)

## Steps to reproduce the issue

1.  regular setup of a Laravel project (composer install/cp env/)
2.  npm/yarn (tried both) install and prod
3.  go to /login or /register

## What is expected?
See the login/register pages

## Additional details / screenshots
![Screenshot 2023-11-28 at 12 24 15](https://github.com/serversideup/financial-freedom/assets/844961/78d89cc7-46f9-4185-8fb8-3f25761d14a0)

**Comment by jaydrogers** [comment]
This project is still a big work in progress. There are a few open source projects that we're wrapping up that will be used to develop this project.

Here is the latest update: https://youtu.be/JKR-zwwaJ1A
